Added support for new datatypes
bigbinary/neeto-filters pull request #45
Opened 2022-06-10 09:08 UTC by AbhayVAshokan

Fixes #40 
The following types have been added/modified:
1. `date`: Accepts date inputs without time using DatePicker.
2. `time`: Accepts time inputs without date using TimePicker.
3. `datetime`: Accepts date and time using DatePicker.
4. `date_range`: Accepts two dates using DatePicker.
5. `time_range`: Accepts two times using TimePicker.
6. `single_option`: Accepts a text using dropdown.
7. `multi_option`: Accepts an array of options using dropdown.

2022-06-10 09:20 UTC, AbhayVAshokan commented
@Amaljith-K _a please review.

2022-06-10 13:40 UTC, Amaljith-K requested changes
@AbhayVAshokan _a

2022-06-10 13:40 UTC, Amaljith-K commented on src/components/FilterDropdown/SearchInput.jsx
> +      };
https://vimeo.com/719093167/25ca1c423d

2022-06-10 13:40 UTC, Amaljith-K commented on src/components/FilterDropdown/SearchInput.jsx
> +  // type = "time" or type = "time_range"
This comment is redundant. It is obvious from the code.

2022-06-10 13:40 UTC, Amaljith-K commented on src/components/FilterDropdown/SearchInput.jsx
> +      };
Are we repeating code here?

2022-06-10 13:40 UTC, Amaljith-K commented on src/components/FilterDropdown/utils.js
> +    return "";
Isn't this enough?
```suggestion
    return error;
```

2022-06-10 13:40 UTC, Amaljith-K commented on src/components/utils.js
> +          : formatTime(value);
Can we move this to a function?
```js
nodeValue = applyFormatting(condition, formatTime);
```

2022-06-10 13:40 UTC, Amaljith-K commented on src/constants.js
> +  [ATTRIBUTE_TYPES.time_range]: ["between", "has_any_value", "is_unknown"],
I don't really understand how `between` rule works for time_range and date_range.
https://vimeo.com/719101765/57fb5c7cd3

2022-06-10 13:40 UTC, Amaljith-K commented on src/constants.js
> +export const MULTI_OPTION_TYPE_REGEX = /^(?:custom\.)?multi_option$/g;
https://vimeo.com/719102401/a24412f316

2022-06-10 15:30 UTC, AbhayVAshokan commented on src/constants.js
> +  [ATTRIBUTE_TYPES.time_range]: ["between", "has_any_value", "is_unknown"],
@Amaljith-K yes, thats a great concern. the `between` filter might raise confusions. My idea was to only filter totally inclusive date or time ranges.
One other approach is to change the set of filters to something like `["starts_between", "ends_between", "has_any_value", "is_unknown"]`. WDYT?

2022-06-10 16:36 UTC, AbhayVAshokan commented
@Amaljith-K _a

2022-06-13 04:55 UTC, Amaljith-K commented on src/constants.js
> +  [ATTRIBUTE_TYPES.time_range]: ["between", "has_any_value", "is_unknown"],
Filter for range datatype should be a single date. 
The rule name can be something like: `date_in_range` (you can find something better).
The user will choose a date. We will find all rows whose date range includes the selected date.

2022-06-13 05:56 UTC, AbhayVAshokan commented
@Amaljith-K I have updated the `between` rule to `contains` for both `date_range` and `time_range` types.

2022-06-13 11:08 UTC, Amaljith-K approved these changes
LGTM

2022-06-13 11:09 UTC, merged